version: '3'

dotenv:
  - .env

tasks:
  build:
    cmds:
         - docker build --pull --rm -f ./api.Dockerfile -t ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME1}:latest '.'
         - docker build --pull --rm -f ./info.Dockerfile -t ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME2}:latest '.'
         - docker build --pull --rm -f ./login.Dockerfile -t ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME3}:latest '.'
         - docker build --pull --rm -f ./root.Dockerfile -t ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME4}:latest '.'

  push:
    cmds:
      - docker tag ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME1}:latest ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME1}:${APP_IMAGE_TAG}
      - docker tag ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME2}:latest ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME2}:${APP_IMAGE_TAG}
      - docker tag ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME3}:latest ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME3}:${APP_IMAGE_TAG}
      - docker tag ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME4}:latest ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME4}:${APP_IMAGE_TAG}
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME1}:${APP_IMAGE_TAG}
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME2}:${APP_IMAGE_TAG}
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME3}:${APP_IMAGE_TAG}
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME4}:${APP_IMAGE_TAG}
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME1}:latest
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME2}:latest
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME3}:latest
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME4}:latest

  deploy:
    cmds: 
    - kubectl apply -f ./deployments/k8s/config-env-api.yaml
    - kubectl apply -f ./deployments/k8s/config-env-info.yaml
    - kubectl apply -f ./deployments/k8s/config-env-login.yaml
    - kubectl apply -f ./deployments/k8s/config-env-root.yaml
    - kubectl apply -f ./services/api-service.yaml 
    - kubectl apply -f ./services/info-service.yaml 
    - kubectl apply -f ./services/login-service.yaml 
    - kubectl apply -f ./services/root-service.yaml 
    - kubectl apply -f ./deployments/k8s/api-deployment.yaml
    - kubectl apply -f ./deployments/k8s/info-deployment.yaml
    - kubectl apply -f ./deployments/k8s/login-deployment.yaml
    - kubectl apply -f ./deployments/k8s/root-deployment.yaml
    - kubectl apply -f ./ingress/ingress.yaml

  release:
    cmds:
      - task: build
      - task: push
      - task: deploy